In [1]:
# importing relevant modules
from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve
from scipy.integrate import solve_ivp
from scipy.optimize import fsolve
import import_ipynb

In [2]:
# The Hopf bifurcation equations 
def Hopf(t,z,b,s):
    u1, u2 = z[0], z[1]
    return np.array([b*u1 - u2 + s*u1*(u1**2 + u2**2), u1 + b*u2 + s*u2*(u1**2 +u2**2)])

In [3]:
# assign values
b = 1
s = -1

In [4]:
def phase_condition_func(func, u, T, args):
    return func(T,u,*args)[0]

In [5]:
#Construct the shooting root-finding problem
def shooting(u0, function, phase_condition,args):
    """
    A function that uses numerical shooting to find limit cycles of
    a specified ODE.

    Parameters
    ----------
     u0 : numpy.array
        An initial guess at the initial values for the limit cycle.
    
    fun : function
        The ODE to apply shooting to. The ode function should take
        a single parameter (the state vector) and return the
        right-hand side of the ODE as a numpy.array.
    
    phase_condition: function
                    The phase condition for the limit cycle.
        
    args: tuple
        arguments passed for the numerical shooting

    Returns
    -------
    Returns a numpy.array containing the corrected initial values
    for the limit cycle. If the numerical root finder failed, the
    returned array is empty.
    """
    u, T = u0[:-1], u0[-1]
    sol = solve_ivp(function, (0,T), u, args = args, rtol = 1e-6)
    final_states = sol.y[:,-1]
    phase = np.array([phase_condition(function,u,T,args)])
    #phase_condition1 = np.array([function(T,u,args[0],args[1],args[2])[0]])
    return np.concatenate((u-final_states, phase))

In [6]:
#find the roots of the system of 2 ODE's with an initial guess
from scipy.optimize import fsolve
root = fsolve(shooting,[1,1,6.2],args = (Hopf, phase_condition_func, (1,-1)))
root

array([ 1.00001055e+00, -2.11038334e-05,  6.28323668e+00])

In [7]:
shooting([1,0,6.2], Hopf, phase_condition_func,args=(1,-1))

array([0.00345289, 0.08314003, 0.        ])

In [8]:
# importing the testing_2ODE function from test_script
from ipynb.fs.full.test_script import testing_2ODE

In [9]:
from test_script import testing_2ODE

importing Jupyter notebook from test_script.ipynb


In [10]:
# call the test function from the testing_2ODE file
# if the test has passed then the roots found are close to the true solution
# if the test has failed then the roots found are not within a tolerance of the true solution
testing_2ODE(shooting,[1,0,6.2],(Hopf,phase_condition_func,(1,-1)))

Test passed


In [11]:
# add another dimension for the Hopf bifurcation equations 
#so that we have a system of 3 ODE's
def k(t,z,b,s):
    u1, u2, u3 = z[0], z[1], z[2]
    return [b*u1 - u2 + s*u1*(u1**2 + u2**2), u1 + b*u2 + s*u2*(u1**2 +u2**2), -u3]

In [12]:
# importing the testing_3ODE function from test_script
from ipynb.fs.full.test_script import testing_3ODE

In [13]:
from test_script import testing_3ODE

In [14]:
# call the test function from the testing_3ODE file
# if the test has passed then the roots found are close to the true solution
# if the test has failed then the roots found are not within a tolerance of the true solution
testing_3ODE(shooting,[3,2,3,6.2],(k,phase_condition_func,(1,-1)))

Test passed


(array([ 1.00001331e+00, -2.66280062e-05, -1.00305059e-31,  5.02659949e+01]),
 [0.9999998686853143, 0.0005124737593983193, 1.478276843684483e-22],
 array([ 1.34446975e-05, -5.39101766e-04, -1.47827684e-22]))

In [ ]:
# Additions needed
# check that your code handles errors gracefully
# Consider errors such as
# providing inputs such that the numerical root finder does not converge.
