In [6]:
# importing relevant modules
from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve
from scipy.integrate import solve_ivp
from scipy.optimize import fsolve
import import_ipynb

In [7]:
# The Hopf bifurcation equations 
def Hopf(t,z,b,s):
    u1, u2 = z[0], z[1]
    return np.array([b*u1 - u2 + s*u1*(u1**2 + u2**2), u1 + b*u2 + s*u2*(u1**2 +u2**2)])

In [8]:
def Hopf_exact(t,z,b,s):
    # the exact solution
    u1 = np.sqrt(b)*np.cos(t+z[-1])
    u2 = np.sqrt(b)*np.sin(t+z[-1])
    return [u1,u2]

In [9]:
# assign values
b = 2
s = -1

In [10]:
def phase_condition_func(func, u, T, args):
    return func(T,u,*args)[0]

In [11]:
#Construct the shooting root-finding problem
def shooting(u0, function, phase_condition,args):
    """
    A function that uses numerical shooting to find limit cycles of
    a specified ODE.

    Parameters
    ----------
     u0 : numpy.array
        An initial guess at the initial values for the limit cycle.
    
    fun : function
        The ODE to apply shooting to. The ode function should take
        a single parameter (the state vector) and return the
        right-hand side of the ODE as a numpy.array.
    
    phase_condition: function
                    The phase condition for the limit cycle.
        
    args: tuple
        arguments passed for the numerical shooting

    Returns
    -------
    Returns a numpy.array containing the corrected initial values
    for the limit cycle. If the numerical root finder failed, the
    returned array is empty.
    """
    u, T = u0[:-1], u0[-1]
    sol = solve_ivp(function, (0,T), u, args = args, rtol = 1e-6)
    final_states = sol.y[:,-1]
    phase = np.array([phase_condition(function,u,T,args)])
    #phase_condition1 = np.array([function(T,u,args[0],args[1],args[2])[0]])
    return np.concatenate((u-final_states, phase))

In [13]:
#find the roots of the system of 2 ODE's with an initial guess
from scipy.optimize import fsolve
root = fsolve(shooting,[1,1,6.2],args = (Hopf, phase_condition_func, (2,-1)))
root

array([ 1.41421405e+00, -1.96665397e-06,  6.28319044e+00])

In [14]:
shooting([1,0,6.2], Hopf, phase_condition_func,args=(2,-1))

array([-0.40932326,  0.11751392,  1.        ])

In [ ]:
# importing the testing_2ODE function from test_script
from ipynb.fs.full.test_script import testing_2ODE

In [ ]:
from test_script import testing_2ODE

In [19]:
# define a test script that runs the shooting code and checks it against its true solution
# works for 2 ODEs
# checking that a function produces the correct output for a given input
def testing_2ODE(solver, initial_guess, args):
    (Hopf,phase_condition_func,(b,s)) = args
    
    # adding tests to check that the code handles errors gracefully
    if np.size(initial_guess) != 3:
        print("must specify 3 input arguments for a system of 2 ODE's")
    else:
    
        root = fsolve(solver, initial_guess, args = args)

        
        # defining the true solution
        true_sol = [np.sqrt(b)*np.cos(initial_guess[-1]+root[-1]), np.sqrt(b)*np.sin(initial_guess[-1]+root[-1])]
        
        
        # calculating the error
        error =  root[:-1] - true_sol

        if np.allclose(error,[0,0]) == True:
            result = print('Test passed')
        else:
            result = print('Test failed')
        return root, true_sol

In [21]:
# define a test script that runs the shooting code and checks it against its true solution
# works for 3 ODEs
# checking that a function produces the correct output for a given input
def testing_3ODE(solver, initial_guess, args):
    (k,phase_condition_func ,(b,s)) = args
    
    # adding tests to check that the code handles errors gracefully
    if np.size(initial_guess) != 4:
        print("must specify 4 input arguments for a system of 3 ODE's")
    else:
    
        root = fsolve(solver, initial_guess,args = args)
        
        # defining the true solution
        true_sol = [np.sqrt(b)*np.cos(initial_guess[-1]+root[-1]), np.sqrt(b)*np.sin(initial_guess[-1]+root[-1]), np.exp(-initial_guess[-1])]
        
        # calculating the error
        error =  root[:-1] - true_sol

        if np.allclose(error,[0,0,0]) == True:
            result = print('Test passed')
        else:
            result = print('Test failed')
        return result

In [20]:
# call the test function from the testing_2ODE file
# if the test has passed then the roots found are close to the true solution
# if the test has failed then the roots found are not within a tolerance of the true solution
testing_2ODE(shooting,[1,0,6.2],(Hopf,phase_condition_func,(2,-1)))

Test failed


(array([ 1.41421405e+00, -1.96663379e-06,  6.28319044e+00]),
 [1.4093239527550896, -0.11749891995576171])

In [22]:
# add another dimension for the Hopf bifurcation equations 
#so that we have a system of 3 ODE's
def k(t,z,b,s):
    u1, u2, u3 = z[0], z[1], z[2]
    return [b*u1 - u2 + s*u1*(u1**2 + u2**2), u1 + b*u2 + s*u2*(u1**2 +u2**2), -u3]

In [ ]:
# importing the testing_3ODE function from test_script
from ipynb.fs.full.test_script import testing_3ODE

In [ ]:
from test_script import testing_3ODE

In [23]:
# call the test function from the testing_3ODE file
# if the test has passed then the roots found are close to the true solution
# if the test has failed then the roots found are not within a tolerance of the true solution
testing_3ODE(shooting,[1,0,0,6.2],(k,phase_condition_func,(b,s)))

Test failed


In [ ]:
# Additions needed
# check that your code handles errors gracefully
# Consider errors such as
# providing inputs such that the numerical root finder does not converge.
